# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-18 12:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('duration', models.DateField(verbose_name='campaign closing date')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(10)])),
                ('total_funds_received', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('campaign_status', models.CharField(max_length=100)),
                ('campaign_image', models.ImageField(blank=True, help_text='Upload a Campaign Image', null=True, upload_to='pic_folder/')),
                ('short_description', models.TextField()),
                ('long_description', models.TextField(blank=True, null=True)),
                ('funds_disbursement_status', models.CharField(max_length=100)),
                ('approval_status', models.CharField(blank=True, choices=[('APPROVE', 'APPROVE'), ('REJECT', 'REJECT'), ('PENDING', 'PENDING')], default='PENDING', max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_approver', to=settings.AUTH_USER_MODEL)),
                ('campaign_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_business_owner', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_rejector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transaction_fee_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], max_length=100)),
                ('transaction_fee', models.DecimalField(decimal_places=2, max_digits=19)),
                ('processing_fee_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], max_length=100)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=19)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Campaign Configurations',
            },
        ),
        migrations.CreateModel(
            name='CampaignDisbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_target', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(null=True, verbose_name='donation date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('disbursement_type', models.CharField(blank=True, choices=[('DISBURSE', 'DISBURSE'), ('REFUND', 'REFUND')], max_length=100, null=True)),
                ('disbursement_method', models.CharField(blank=True, choices=[('MPESA', 'MPESA'), ('PAYPAL', 'PAYPAL')], max_length=100, null=True)),
                ('disbursement_status', models.CharField(max_length=100)),
                ('recipient_email', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('APPROVE', 'APPROVE'), ('REJECT', 'REJECT'), ('PENDING', 'PENDING')], default='PENDING', max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('disbursement_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('disbursed', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_approver', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.Campaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_recipient', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_rejector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Campaign Disbursements',
            },
        ),
        migrations.CreateModel(
            name='CampaignPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='donation date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('allow_visibility', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.Campaign')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_donator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Campaign Payments',
            },
        ),
        migrations.CreateModel(
            name='CampaignSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Campaign Sectors',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CampaignSector'),
        ),
    ]
