# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-19 11:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='reward notification date')),
                ('reward', models.TextField()),
                ('reward_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Campaign Rewards',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_reward_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_reward_threshold',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(blank=True, choices=[('REWARD BASED', 'REWARD BASED'), ('NON-REWARD BASED', 'NON-REWARD BASED')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaigndisbursement',
            name='campaign_duration',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 11, 41, 30, 583262, tzinfo=utc), verbose_name='campaign closing date'),
        ),
        migrations.AlterField(
            model_name='campaigndisbursement',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='disbursement request date'),
        ),
        migrations.AddField(
            model_name='campaignreward',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.Campaign'),
        ),
        migrations.AddField(
            model_name='campaignreward',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CampaignPayment'),
        ),
        migrations.AddField(
            model_name='campaignreward',
            name='rewarded_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewarded_donator', to=settings.AUTH_USER_MODEL),
        ),
    ]
