# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0003_auto_20190625_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndisbursement',
            name='campaign_duration',
            field=models.DateField(default=datetime.datetime(2019, 6, 25, 15, 57, 54, 299026, tzinfo=utc), verbose_name='campaign closing date'),
        ),
    ]
