# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0005_auto_20190625_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndisbursement',
            name='campaign_duration',
            field=models.DateField(default=datetime.datetime(2019, 6, 25, 16, 23, 9, 286595, tzinfo=utc), verbose_name='campaign closing date'),
        ),
    ]
