# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 17:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0010_auto_20190625_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignpayment',
            name='donator_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignpayment',
            name='donator_phoneno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignreward',
            name='rewarded_user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_reward_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_reward_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndisbursement',
            name='campaign_duration',
            field=models.DateField(default=datetime.datetime(2019, 6, 25, 17, 22, 28, 162215, tzinfo=utc), verbose_name='campaign closing date'),
        ),
        migrations.AlterField(
            model_name='campaignpayment',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_donator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaignreward',
            name='rewarded_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewarded_donator', to=settings.AUTH_USER_MODEL),
        ),
    ]
