# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0011_auto_20190625_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndisbursement',
            name='campaign_duration',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 8, 16, 49, 823863, tzinfo=utc), verbose_name='campaign closing date'),
        ),
    ]
