# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-08 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0015_auto_20190701_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='minimum_donation',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AddField(
            model_name='campaignpayment',
            name='payment_payer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndisbursement',
            name='campaign_duration',
            field=models.DateField(null=True, verbose_name='campaign closing date'),
        ),
    ]
