# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-21 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0016_auto_20190708_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(null=True, verbose_name='token generate date')),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Mpesa Api Token',
            },
        ),
        migrations.CreateModel(
            name='MpesaC2BNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='c2b notification date')),
                ('account_name', models.CharField(max_length=255)),
                ('amount_received', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('reference_code', models.CharField(max_length=255)),
                ('shortcode', models.CharField(max_length=255)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CampaignPayment')),
            ],
            options={
                'verbose_name_plural': 'Mpesa C2B Notification',
            },
        ),
        migrations.CreateModel(
            name='MpesaC2BRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(null=True, verbose_name='c2b register date')),
                ('request_json', models.TextField()),
                ('response_json', models.TextField()),
                ('response_code', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Mpesa C2B Registration',
            },
        ),
        migrations.CreateModel(
            name='MpesaSTKPush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(null=True, verbose_name='reward notification date')),
                ('request_json', models.TextField()),
                ('response_json', models.TextField()),
                ('response_code', models.IntegerField()),
                ('checkoutID', models.TextField(blank=True, null=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CampaignPayment')),
            ],
            options={
                'verbose_name_plural': 'Mpesa STK Push',
            },
        ),
        migrations.CreateModel(
            name='MpesaSTKResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(null=True, verbose_name='stk response date')),
                ('response_json', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Mpesa STK Response',
            },
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(blank=True, choices=[('REWARD BASED', 'REWARD BASED'), ('DONATION BASED', 'DONATION BASED')], max_length=100, null=True),
        ),
    ]
