# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venturelift_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporterprofile',
            name='interest_sectors',
        ),
        migrations.AddField(
            model_name='supporterprofile',
            name='interest_sectors',
            field=models.CharField(blank=True, choices=[('AGRIBUSINESS', 'AGRIBUSINESS'), ('CREATIVE', 'CREATIVE'), ('EDUCATION', 'EDUCATION'), ('FINANCIAL SERVICES', 'FINANCIAL SERVICES'), ('FMCG - RETAIL', 'FMCG - RETAIL'), ('HEALTH', 'HEALTH'), ('HOUSING & REAL ESTATE', 'HOUSING & REAL ESTATE'), ('RENEWABLE ENERGY', 'RENEWABLE ENERGY'), ('TECHNOLOGY', 'TECHNOLOGY'), ('WATER and SANITATION', 'WATER and SANITATION')], help_text='Target Sectors', max_length=250, null=True),
        ),
    ]
