# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-22 13:43
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venturelift_profiles', '0002_auto_20200222_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporterprofile',
            name='interest_sectors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AGRIBUSINESS', 'AGRIBUSINESS'), ('CREATIVE', 'CREATIVE'), ('EDUCATION', 'EDUCATION'), ('FINANCIAL SERVICES', 'FINANCIAL SERVICES'), ('FMCG - RETAIL', 'FMCG - RETAIL'), ('HEALTH', 'HEALTH'), ('HOUSING & REAL ESTATE', 'HOUSING & REAL ESTATE'), ('RENEWABLE ENERGY', 'RENEWABLE ENERGY'), ('TECHNOLOGY', 'TECHNOLOGY'), ('WATER and SANITATION', 'WATER and SANITATION')], help_text='Target Sectors', max_length=250, null=True),
        ),
    ]
